Create Table If Not Exists addresses(
    ADD_PK_AddressId Int Not Null Primary Key Auto_Increment,
    ADD_FK_AddressType int Not Null,
    ADD_FK_ResidenceType int Not Null,
    ADD_FK_PublicPlaceType int Not Null,
    ADD_STR_PublicPlace Varchar(70) Not Null,
    ADD_STR_Neighborhood Varchar(70) Not Null,
    ADD_STR_Number Char(3) Not Null,
    ADD_STR_CEP Char(8) Not Null,
    ADD_STR_City Varchar(70) Not Null,
    ADD_STR_State Varchar(70) Not Null,
    ADD_STR_Country Varchar(70) Not Null,
    ADD_STR_Notes Varchar(255),
    ADD_BOL_Active TinyInt Not Null Default 1,
    ADD_DTT_CreateDateTime DateTime not Null Default now(),
    ADD_DTT_UpdateDateTime DateTime not Null Default now(),
    FOREIGN KEY (ADD_FK_ResidenceType) REFERENCES ResidenceTypes(RDT_PK_ResidenceTypeId),
    FOREIGN KEY (ADD_FK_PublicPlaceType) REFERENCES PublicPlaceTypes(PPT_PK_PublicPlaceTypeId),
    FOREIGN KEY (ADD_FK_AddressType) REFERENCES AddressTypes(ATP_PK_AddressTypeId)
);